#!/usr/bin/env bash
#
# Regenerate the two files that describe Cloudflare to this host, from
# Cloudflare's published ranges:
#
#   nginx/snippets/cloudflare-real-ip.conf   who may declare the client address
#   ufw/cloudflare-ranges.txt                who may reach ports 80 and 443
#
# The snippet tells nginx which peers are allowed to declare the real client
# address. Cloudflare adds ranges from time to time, and a stale list is a quiet
# failure: requests arriving from a new range keep Cloudflare's own address as
# the client, so every visitor behind it shares one identity and anything keyed
# on client address stops discriminating.
#
# The ranges file is the firewall's copy of the same answer. Stale there is a
# loud failure rather than a quiet one: a new Cloudflare range cannot reach the
# origin at all, and the site is down from part of the internet. Both come from
# one fetch and one review so they cannot disagree.
#
# Run it, review the diff, commit, then apply:
#   ./scripts/update-cloudflare-ips.sh
#   sudo ./scripts/apply-nginx.sh
#   sudo ./ufw/rules.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/nginx/snippets/cloudflare-real-ip.conf"
RANGES="$ROOT/ufw/cloudflare-ranges.txt"
TMP="$(mktemp)"
TMP_RANGES="$(mktemp)"
trap 'rm -f "$TMP" "$TMP_RANGES"' EXIT

fetch() {
  curl -fsS --max-time 30 "$1" || { echo "Could not fetch $1" >&2; exit 1; }
}

V4="$(fetch https://www.cloudflare.com/ips-v4)"
V6="$(fetch https://www.cloudflare.com/ips-v6)"

# A truncated response would silently shrink the trusted set, so require both
# lists to look sane before overwriting anything.
[[ "$(grep -c . <<<"$V4")" -ge 10 ]] || { echo "IPv4 list looks too short, refusing" >&2; exit 1; }
[[ "$(grep -c . <<<"$V6")" -ge 5 ]] || { echo "IPv6 list looks too short, refusing" >&2; exit 1; }

{
  echo "# Generated by scripts/update-cloudflare-ips.sh on $(date -I). Do not edit by hand."
  echo "#"
  echo "# Included in every server block. Only peers in these ranges may declare the"
  echo "# real client address, so a request that reaches the origin directly keeps its"
  echo "# own socket address and cannot claim to be someone else."
  echo "#"
  echo "# Hosts that are not proxied by Cloudflare, staging among them, are unaffected:"
  echo "# their peer is not in this set, so no rewrite happens."
  echo
  while read -r cidr; do
    [[ -n "$cidr" ]] && echo "set_real_ip_from $cidr;"
  done <<<"$V4"
  echo
  while read -r cidr; do
    [[ -n "$cidr" ]] && echo "set_real_ip_from $cidr;"
  done <<<"$V6"
  echo
  echo "# Cloudflare sets this to the connecting client. Preferred over"
  echo "# X-Forwarded-For, which is a list a client can prepend to."
  echo "real_ip_header CF-Connecting-IP;"
} > "$TMP"

{
  echo "# Generated by scripts/update-cloudflare-ips.sh on $(date -I). Do not edit by hand."
  echo "#"
  echo "# The only sources allowed to reach ports 80 and 443, applied by ufw/rules.sh."
  echo "# Every name this host serves is proxied by Cloudflare, so a connection from"
  echo "# anywhere else is one that skipped it."
  echo "$V4"
  echo "$V6"
} > "$TMP_RANGES"

mv "$TMP" "$OUT"
mv "$TMP_RANGES" "$RANGES"
trap - EXIT
echo "Wrote $OUT"
echo "Wrote $RANGES"
grep -c "^set_real_ip_from" "$OUT" | xargs echo "Trusted ranges:"
